name: build_java
on: 
  push:
    branches:
      - main
     workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu:alpine
    steps:
      - uses: actions/checkout@v2
      
      - name: Run echo 
        run: sudo echo 'It just works.'

