# This is a basic workflow to help you get started with Actions

name: CI_CD

# Controls when the workflow will run
on:
  schedule:
  - cron: "30 8 * * 1"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run shellcheak 
        run: |
          sudo apt-get install xz-utils
          sudo tar xvf shellcheck-latest.linux.x86_64.tar.xz
          sudo ./shellcheck-latest/shellcheck --version

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,

