# This is a basic workflow to help you get started with Actions

name: CI_CD

# Controls when the workflow will run
on:
  push:
    branches: 
      - master
  schedule:
  - cron: "30 8 * * 1"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run shellcheck 
        run: sudo apt-get install shellcheck

      - name: Shellcheck check
        run: sudo shellcheck pre_deploy.sh >> shellcheck-report.sh

